/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "flex",
    "justify-center",
    "items-center",
    "gap-4",
    "grid",
    "grid-cols-1",
    "grid-cols-2",
    "md:grid-cols-2",
    "gap-4",
    "gap-6",
    "gap-8",
    "p-4",
    "p-6",
    "aspect-square",
    "w-full",
    "h-full",
    "object-cover",
    "grid",
    "grid-cols-1",
    "lg:grid-cols-12",
    "lg:col-span-8",
    "lg:col-span-4",
    "gap-12",
    "text-sm",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
